---
# tasks file for ansible-role-nginx_controller_user_role

- name: Fail if required variables are not defined
  assert:
    that: item is in vars and vars[item] | length > 0
  loop:
    - nginx_controller_api_version
    - nginx_controller_fqdn
    - nginx_controller_auth_token
    - nginx_controller_user_role.metadata.name

- name: Form the user role url
  set_fact:
    nginx_controller_user_role_url: >-
      https://{{ nginx_controller_fqdn }}/{{ nginx_controller_api_version }}/platform/roles/{{ nginx_controller_user_role.metadata.name }}

- name: Upsert the role definition
  uri:
    url: "{{ nginx_controller_user_role_url }}"
    method: "PUT"
    body: "{{ nginx_controller_user_role }}"
    body_format: json
    status_code:
      - 200
      - 201
      - 202
    return_content: true
    validate_certs: "{{ nginx_controller_validate_certs | default(false) }}"
    headers:
      Cookie: "{{ nginx_controller_auth_token }}"
  register: nginx_controller_user_role_current_status
  ignore_errors: false
